import { StyleSheet } from 'react-native';

export const homeStyles = (theme, fontSizeMultiplier = 1, dyslexicEnabled = false) => StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
  },
  header: {
    marginBottom: 24,
  },
  title: {
    fontSize: 24 * fontSizeMultiplier,
    color: theme.colors.text,
    marginBottom: 8,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : (theme.fontFamily || 'System'),
    fontWeight: dyslexicEnabled ? 'normal' : 'bold',
  },
  subtitle: {
    fontSize: 16 * fontSizeMultiplier,
    color: theme.colors.muted,
    marginBottom: 16,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.card,
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 16 * fontSizeMultiplier,
    color: theme.colors.text,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  searchButton: {
    backgroundColor: theme.colors.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  searchButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15 * fontSizeMultiplier,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  statBox: {
    flex: 1,
    backgroundColor: theme.colors.card,
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 4,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 22 * fontSizeMultiplier,
    fontWeight: 'bold',
    color: theme.colors.primary,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  statLabel: {
    fontSize: 14 * fontSizeMultiplier,
    color: theme.colors.muted,
    marginTop: 4,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  sectionTitle: {
    fontSize: 18 * fontSizeMultiplier,
    color: theme.colors.text,
    marginBottom: 16,
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : (theme.fontFamily || 'System'),
    fontWeight: dyslexicEnabled ? 'normal' : 'bold',
  },
  categoriesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  categoryCard: {
    width: '48%',
    backgroundColor: theme.colors.card,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  categoryName: {
    marginTop: 8,
    fontSize: 14 * fontSizeMultiplier,
    fontWeight: '600',
    color: theme.colors.text,
    textAlign: 'center',
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
  stepsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  stepBox: {
    width: '48%',
    backgroundColor: theme.colors.card,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: 'center',
  },
  stepText: {
    marginTop: 8,
    fontSize: 15 * fontSizeMultiplier,
    color: theme.colors.text,
    textAlign: 'center',
    fontFamily: dyslexicEnabled ? 'OpenDyslexic' : theme.fontFamily || 'System',
  },
});
